name: minio
description: Unofficial MinIO Dart Client SDK that provides simple APIs to access any Amazon S3 compatible object storage server.
version: 3.5.0
homepage: https://github.com/xtyxtyx/minio-dart
issue_tracker: https://github.com/xtyxtyx/minio-dart/issues

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.1
  # http: ^1.0.0
  # crypto: ^3.0.0
  crypto: ^3.0.3
  # convert: ^3.0.0
  convert: ^3.1.1
  # xml: ^5.0.2
  xml: ^6.2.2
  buffer: ^1.1.0
  # intl: ^0.17.0
  intl: ^0.18.1
  mime: ^1.0.0
  # mime: ^1.0.4
  path: ^1.8.0
  # path: ^1.8.3

dev_dependencies:
  # pedantic: ^1.11.0
  flutter_lints: ^2.0.0
  # test: ^1.16.8
  test: ^1.24.9
  # html: ^0.15.0
  html: ^0.15.4
